dist: xenial
language: elixir
elixir:
  - 1.6.2
otp_release:
  - 20.2.2

env:
  - MIX_ENV=test LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.libsodium/lib:$HOME/.libsodium/include PATH=$PATH:$HOME/.libsodium/lib:$HOME/.libsodium/include LIBRARY_PATH=$LIBRARY_PATH:$HOME/.libsodium/lib:$HOME/.libsodium/include C_INCLUDE_PATH=$C_INCLUDE_PATH:$HOME/.libsodium/lib:$HOME/.libsodium/include

before_install:
  - wget -O libsodium-src.tar.gz https://github.com/jedisct1/libsodium/releases/download/1.0.16/libsodium-1.0.16.tar.gz
  - mkdir libsodium-src && tar -zxf libsodium-src.tar.gz -C libsodium-src --strip-components=1
  - cd libsodium-src && ./configure --prefix=$HOME/.libsodium && make -j$(nproc) && make install && cd ..
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env

script:
  - mix compile --warnings-as-errors
  - mix credo list
  - mix format --check-formatted
  - mix coveralls -u
  - mix dialyzer --halt-exit-status

cache:
  directories:
    - $HOME/.cargo
    - deps
    - _build
